/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab6p2_lisadiazdelvalle;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author HTS
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(this);
        
        ap.cargar();
        usuarios= ap.getUsers();
        
        cancion.cargarCancion();
        canciones = cancion.getCanciones();
        
        lanzamiento.cargarLan();
        lanzamientos = lanzamiento.getLanzamientos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JF_SignupArtista = new javax.swing.JFrame();
        JP_SignupArtista = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JT_NombreArtista = new javax.swing.JTextField();
        PF_passArtista = new javax.swing.JPasswordField();
        JB_SignupArtista = new javax.swing.JButton();
        JT_UserArtista = new javax.swing.JTextField();
        JB_AtrasArtista = new javax.swing.JButton();
        Spinner_EdadArtista = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        JF_SignupCliente = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        JT_UserCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PF_passCliente = new javax.swing.JPasswordField();
        JB_SignupCliente = new javax.swing.JButton();
        JB_AtrasCliente = new javax.swing.JButton();
        Spinner_EdadCliente = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        JF_Artista = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        JB_CrearLanza = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        JB_Crud = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        JD_NuevoLanzamiento = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        JB_CrearLanzamiento = new javax.swing.JButton();
        JB_AtrasNuevoLanza = new javax.swing.JButton();
        JT_Titulo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JT_Fecha = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CB_Tipo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        JD_Cancion = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        JT_DuracionCancion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        JT_TituloCancion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        JT_ReferenciaSingle = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        JB_CrearCancion = new javax.swing.JButton();
        JF_ListaLanzamientos = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        PP_CrudLanza = new javax.swing.JPopupMenu();
        MI_Publicar = new javax.swing.JMenuItem();
        MI_Eliminar = new javax.swing.JMenuItem();
        MI_Editar = new javax.swing.JMenuItem();
        JP_Login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JT_UserLogin = new javax.swing.JTextField();
        PF_Login = new javax.swing.JPasswordField();
        JB_Login = new javax.swing.JButton();
        JL_SignupArtista = new javax.swing.JLabel();
        JL_SignupCliente = new javax.swing.JLabel();

        JF_SignupArtista.setTitle("Artista");

        JP_SignupArtista.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 0));
        jLabel2.setText("Sign Up Artista");

        JT_NombreArtista.setForeground(new java.awt.Color(204, 204, 204));
        JT_NombreArtista.setText("Nombre");

        PF_passArtista.setForeground(new java.awt.Color(204, 204, 204));
        PF_passArtista.setText("jPasswordField1");

        JB_SignupArtista.setBackground(new java.awt.Color(153, 255, 0));
        JB_SignupArtista.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        JB_SignupArtista.setText("Sign Up");
        JB_SignupArtista.setActionCommand("");
        JB_SignupArtista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_SignupArtistaMouseClicked(evt);
            }
        });

        JT_UserArtista.setForeground(new java.awt.Color(204, 204, 204));
        JT_UserArtista.setText("Username");

        JB_AtrasArtista.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        JB_AtrasArtista.setText("Atras");
        JB_AtrasArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AtrasArtistaActionPerformed(evt);
            }
        });

        Spinner_EdadArtista.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        Spinner_EdadArtista.setModel(new javax.swing.SpinnerNumberModel(18, 18, null, 1));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 0));
        jLabel4.setText("Edad (+18)");

        javax.swing.GroupLayout JP_SignupArtistaLayout = new javax.swing.GroupLayout(JP_SignupArtista);
        JP_SignupArtista.setLayout(JP_SignupArtistaLayout);
        JP_SignupArtistaLayout.setHorizontalGroup(
            JP_SignupArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_SignupArtistaLayout.createSequentialGroup()
                .addGroup(JP_SignupArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_SignupArtistaLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(JB_AtrasArtista))
                    .addGroup(JP_SignupArtistaLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(JB_SignupArtista))
                    .addGroup(JP_SignupArtistaLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(JP_SignupArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JP_SignupArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PF_passArtista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JT_UserArtista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JT_NombreArtista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Spinner_EdadArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(JP_SignupArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_SignupArtistaLayout.createSequentialGroup()
                    .addGap(165, 165, 165)
                    .addComponent(jLabel2)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        JP_SignupArtistaLayout.setVerticalGroup(
            JP_SignupArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_SignupArtistaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(JB_AtrasArtista)
                .addGap(68, 68, 68)
                .addComponent(JT_NombreArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JT_UserArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PF_passArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(Spinner_EdadArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JB_SignupArtista)
                .addGap(62, 62, 62))
            .addGroup(JP_SignupArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JP_SignupArtistaLayout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(331, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout JF_SignupArtistaLayout = new javax.swing.GroupLayout(JF_SignupArtista.getContentPane());
        JF_SignupArtista.getContentPane().setLayout(JF_SignupArtistaLayout);
        JF_SignupArtistaLayout.setHorizontalGroup(
            JF_SignupArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_SignupArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JF_SignupArtistaLayout.setVerticalGroup(
            JF_SignupArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_SignupArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        JT_UserCliente.setForeground(new java.awt.Color(204, 204, 204));
        JT_UserCliente.setText("Username");

        jLabel3.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 0));
        jLabel3.setText("Sign Up Cliente");

        PF_passCliente.setForeground(new java.awt.Color(204, 204, 204));
        PF_passCliente.setText("jPasswordField1");

        JB_SignupCliente.setBackground(new java.awt.Color(153, 255, 0));
        JB_SignupCliente.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        JB_SignupCliente.setText("Sign Up");
        JB_SignupCliente.setActionCommand("");
        JB_SignupCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_SignupClienteMouseClicked(evt);
            }
        });

        JB_AtrasCliente.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        JB_AtrasCliente.setText("Atras");
        JB_AtrasCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AtrasClienteActionPerformed(evt);
            }
        });

        Spinner_EdadCliente.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        Spinner_EdadCliente.setModel(new javax.swing.SpinnerNumberModel(12, 12, null, 1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 0));
        jLabel5.setText("Edad (+12)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(JB_AtrasCliente))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Spinner_EdadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(PF_passCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addComponent(jLabel3))
                                    .addComponent(JT_UserCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(JB_SignupCliente)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(JB_AtrasCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JT_UserCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(PF_passCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(Spinner_EdadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(JB_SignupCliente)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout JF_SignupClienteLayout = new javax.swing.GroupLayout(JF_SignupCliente.getContentPane());
        JF_SignupCliente.getContentPane().setLayout(JF_SignupClienteLayout);
        JF_SignupClienteLayout.setHorizontalGroup(
            JF_SignupClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JF_SignupClienteLayout.setVerticalGroup(
            JF_SignupClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 0));
        jLabel6.setText("Bienvenido");

        JB_CrearLanza.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        JB_CrearLanza.setText("Crear Lanzamiento");
        JB_CrearLanza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CrearLanzaActionPerformed(evt);
            }
        });

        jButton6.setText("Atras");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        JB_Crud.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        JB_Crud.setText("Publicar Lanzamiento");
        JB_Crud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CrudActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jButton8.setText("Eliminar");

        jButton9.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jButton9.setText("Editar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JB_Crud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JB_CrearLanza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(35, 35, 35)
                .addComponent(JB_CrearLanza)
                .addGap(26, 26, 26)
                .addComponent(JB_Crud)
                .addGap(27, 27, 27)
                .addComponent(jButton8)
                .addGap(27, 27, 27)
                .addComponent(jButton9)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JF_ArtistaLayout = new javax.swing.GroupLayout(JF_Artista.getContentPane());
        JF_Artista.getContentPane().setLayout(JF_ArtistaLayout);
        JF_ArtistaLayout.setHorizontalGroup(
            JF_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JF_ArtistaLayout.setVerticalGroup(
            JF_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 0));
        jLabel7.setText("Nuevo Lanzamiento");

        JB_CrearLanzamiento.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        JB_CrearLanzamiento.setText("Crear ");
        JB_CrearLanzamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_CrearLanzamientoMouseClicked(evt);
            }
        });

        JB_AtrasNuevoLanza.setText("Atras");
        JB_AtrasNuevoLanza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AtrasNuevoLanzaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 0));
        jLabel8.setText("Titulo");

        jLabel9.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 0));
        jLabel9.setText("Fecha");

        CB_Tipo.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        CB_Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Album", "Single", " " }));

        jLabel10.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 255, 0));
        jLabel10.setText("Tipo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(JB_AtrasNuevoLanza)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(CB_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(JB_CrearLanzamiento))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JT_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JT_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_AtrasNuevoLanza))
                .addGap(11, 11, 11)
                .addComponent(jLabel8)
                .addGap(12, 12, 12)
                .addComponent(JT_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(12, 12, 12)
                .addComponent(JT_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(JB_CrearLanzamiento)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CB_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout JD_NuevoLanzamientoLayout = new javax.swing.GroupLayout(JD_NuevoLanzamiento.getContentPane());
        JD_NuevoLanzamiento.getContentPane().setLayout(JD_NuevoLanzamientoLayout);
        JD_NuevoLanzamientoLayout.setHorizontalGroup(
            JD_NuevoLanzamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_NuevoLanzamientoLayout.setVerticalGroup(
            JD_NuevoLanzamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_NuevoLanzamientoLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        jLabel11.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 255, 0));
        jLabel11.setText("Nueva Cancion");

        jLabel12.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 255, 0));
        jLabel12.setText("Titulo");

        jLabel13.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 255, 0));
        jLabel13.setText("Duracion");

        jLabel14.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 255, 0));
        jLabel14.setText("Referencia al single");

        JB_CrearCancion.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        JB_CrearCancion.setText("Crear ");
        JB_CrearCancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_CrearCancionMouseClicked(evt);
            }
        });
        JB_CrearCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CrearCancionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JT_ReferenciaSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JT_TituloCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JT_DuracionCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(JB_CrearCancion)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addGap(38, 38, 38)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JT_TituloCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JT_DuracionCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JT_ReferenciaSingle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(JB_CrearCancion)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_CancionLayout = new javax.swing.GroupLayout(JD_Cancion.getContentPane());
        JD_Cancion.getContentPane().setLayout(JD_CancionLayout);
        JD_CancionLayout.setHorizontalGroup(
            JD_CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_CancionLayout.setVerticalGroup(
            JD_CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel15.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 255, 0));
        jLabel15.setText("TUS HITS");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Lanzamientos");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Albums");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Singles");
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JF_ListaLanzamientosLayout = new javax.swing.GroupLayout(JF_ListaLanzamientos.getContentPane());
        JF_ListaLanzamientos.getContentPane().setLayout(JF_ListaLanzamientosLayout);
        JF_ListaLanzamientosLayout.setHorizontalGroup(
            JF_ListaLanzamientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JF_ListaLanzamientosLayout.setVerticalGroup(
            JF_ListaLanzamientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MI_Publicar.setText("Publicar");
        MI_Publicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_PublicarActionPerformed(evt);
            }
        });
        PP_CrudLanza.add(MI_Publicar);

        MI_Eliminar.setText("Eliminar");
        MI_Eliminar.setToolTipText("");
        PP_CrudLanza.add(MI_Eliminar);

        MI_Editar.setText("Editar");
        PP_CrudLanza.add(MI_Editar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JP_Login.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Roboto Light", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 0));
        jLabel1.setText("Spotify");

        JT_UserLogin.setForeground(new java.awt.Color(204, 204, 204));
        JT_UserLogin.setText("Username");

        PF_Login.setForeground(new java.awt.Color(204, 204, 204));
        PF_Login.setText("jPasswordField1");

        JB_Login.setBackground(new java.awt.Color(153, 255, 0));
        JB_Login.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        JB_Login.setText("Login");
        JB_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_LoginMouseClicked(evt);
            }
        });
        JB_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_LoginActionPerformed(evt);
            }
        });

        JL_SignupArtista.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        JL_SignupArtista.setForeground(new java.awt.Color(153, 255, 0));
        JL_SignupArtista.setText("Sign up Artista");
        JL_SignupArtista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JL_SignupArtistaMouseClicked(evt);
            }
        });

        JL_SignupCliente.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        JL_SignupCliente.setForeground(new java.awt.Color(153, 255, 0));
        JL_SignupCliente.setText("Sign up Cliente");
        JL_SignupCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JL_SignupClienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JP_LoginLayout = new javax.swing.GroupLayout(JP_Login);
        JP_Login.setLayout(JP_LoginLayout);
        JP_LoginLayout.setHorizontalGroup(
            JP_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_LoginLayout.createSequentialGroup()
                .addGroup(JP_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JP_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JP_LoginLayout.createSequentialGroup()
                            .addGap(254, 254, 254)
                            .addComponent(JB_Login))
                        .addGroup(JP_LoginLayout.createSequentialGroup()
                            .addGap(115, 115, 115)
                            .addGroup(JP_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(PF_Login)
                                .addComponent(JT_UserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(JP_LoginLayout.createSequentialGroup()
                            .addGap(179, 179, 179)
                            .addComponent(JL_SignupArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(JL_SignupCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JP_LoginLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addGap(96, 96, 96)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        JP_LoginLayout.setVerticalGroup(
            JP_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_LoginLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(JT_UserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(PF_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(JB_Login)
                .addGap(18, 18, 18)
                .addGroup(JP_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_SignupArtista)
                    .addComponent(JL_SignupCliente))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JL_SignupArtistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_SignupArtistaMouseClicked
        this.setVisible(false);
        JF_SignupArtista.pack();
        JF_SignupArtista.setLocationRelativeTo(this);
        JF_SignupArtista.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        JF_SignupArtista.setVisible(true);
    }//GEN-LAST:event_JL_SignupArtistaMouseClicked

    private void JL_SignupClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_SignupClienteMouseClicked
        this.setVisible(false);
        JF_SignupCliente.pack();
        JF_SignupCliente.setLocationRelativeTo(this);
        JF_SignupCliente.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        JF_SignupCliente.setVisible(true);
    }//GEN-LAST:event_JL_SignupClienteMouseClicked

    private void JB_AtrasArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AtrasArtistaActionPerformed
        JF_SignupArtista.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_JB_AtrasArtistaActionPerformed

    private void JB_AtrasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AtrasClienteActionPerformed
        JF_SignupCliente.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_JB_AtrasClienteActionPerformed

    private void JB_SignupClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_SignupClienteMouseClicked
        try {
            if ((Integer) Spinner_EdadCliente.getValue() >= 12 && SameUser(JT_UserCliente.getText()) == false) {
                u = new oyente(JT_UserCliente.getText(), PF_passCliente.getText(), "Cliente", ((Integer) Spinner_EdadCliente.getValue()));
                //usuarios.add(u);
//                admin ap
//                        = new admin("./Usuarios.txt");
//                ap.cargar();
                int edad;
                String user, nombre, pass;
                edad = (Integer) Spinner_EdadArtista.getValue();
                user = JT_UserArtista.getText();
                pass = PF_passArtista.getText();
                nombre = JT_NombreArtista.getText();
                Usuario p = new oyente(user, pass, "Cliente", edad);
                ap.getUsers().add(p);
                ap.escribirArchivo();
                JOptionPane.showMessageDialog(JF_SignupCliente, "Cuenta creada exitosamente");
            } else if ((Integer) Spinner_EdadCliente.getValue() < 12) {
                JOptionPane.showMessageDialog(JF_SignupCliente, "Debe de ser mayor de 12");

            } else if (SameUser(JT_UserCliente.getText()) == true) {
                JOptionPane.showMessageDialog(JF_SignupCliente, "Este usuario ya existe");
            }
            JT_UserCliente.setText("");
            PF_passCliente.setText("");
            Spinner_EdadCliente.setValue(0);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_JB_SignupClienteMouseClicked

    private void JB_SignupArtistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_SignupArtistaMouseClicked
        try {
            if ( SameUser(JT_UserArtista.getText()) == false) {
                u = new Artista(JT_UserArtista.getText(), PF_passArtista.getText(), JT_NombreArtista.getText(), "Artista", ((Integer) Spinner_EdadArtista.getValue()));
                //usuarios.add(u);              
                //ap.cargar();
                int edad;
                String user, nombre, pass;
                edad = (Integer) Spinner_EdadArtista.getValue();
                user = JT_UserArtista.getText();
                pass = PF_passArtista.getText();
                nombre = JT_NombreArtista.getText();
                Usuario p = new Artista(user,pass, nombre, "Artista", edad);
                ap.getUsers().add(p);
                ap.escribirArchivo();
                JOptionPane.showMessageDialog(JF_SignupCliente, "Cuenta creada exitosamente");
            }
//            } else if ((Integer) Spinner_EdadCliente.getValue() < 18) {
//                JOptionPane.showMessageDialog(JF_SignupCliente, "Debe de ser mayor de 18");
//
//            } else if (SameUser(JT_UserArtista.getText()) == true) {
//                JOptionPane.showMessageDialog(JF_SignupCliente, "Este usuario ya existe");
//            }

            JT_NombreArtista.setText("");
            JT_UserArtista.setText("");
            PF_passArtista.setText("");
            Spinner_EdadArtista.setValue(0);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_JB_SignupArtistaMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        JF_Artista.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void JB_AtrasNuevoLanzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AtrasNuevoLanzaActionPerformed
        JD_NuevoLanzamiento.setVisible(false);
        JF_Artista.setVisible(true);
    }//GEN-LAST:event_JB_AtrasNuevoLanzaActionPerformed

    private void JB_CrearLanzamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_CrearLanzamientoMouseClicked
        try {
            if (((String) CB_Tipo.getSelectedItem()).equals("Album")) {
                l = new Album(0, JT_Titulo.getText(), JT_Fecha.getText(), 0, "Album");
               // lanzamientos.add(l);
                int cant, likes;
                String titulo, fecha, tipo;
                cant =  0 ;
                titulo = JT_Titulo.getText();
                fecha = JT_Fecha.getText();
                likes= 0;
                Lanzamiento album = new Album(cant,titulo, fecha, likes, "Album");
                lanzamiento.getLanzamientos().add(album);
                lanzamiento.escribirArchivoLan();
                JOptionPane.showMessageDialog(JD_NuevoLanzamiento, "Album creado con exito");
             
 
                DefaultTreeModel modelo = (DefaultTreeModel) jTree1.getModel();
                DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
                DefaultMutableTreeNode nodoNombre;
                nodoNombre = new DefaultMutableTreeNode(l);
                switch (CB_Tipo.getSelectedItem().toString()) {
                    case "Album":
                        ((DefaultMutableTreeNode) raiz.getChildAt(0)).add(nodoNombre);
                        break;
                }
                modelo.reload();
                JT_Titulo.setText("");
                JT_Fecha.setText("");
                JD_NuevoLanzamiento.setVisible(false);
                JF_Artista.pack();
                JF_Artista.setLocationRelativeTo(this);
                JF_Artista.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                JF_Artista.setVisible(true);
            } else if (((String) CB_Tipo.getSelectedItem()).equals("Single")) {
                JD_NuevoLanzamiento.setVisible(false);
                JD_Cancion.pack();
                JD_Cancion.setLocationRelativeTo(this);
                JD_Cancion.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                JD_Cancion.setVisible(true);

            }
        } catch (Exception e) {
        }


    }//GEN-LAST:event_JB_CrearLanzamientoMouseClicked

    private void JB_CrearCancionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_CrearCancionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_CrearCancionMouseClicked

    private void JB_CrearCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CrearCancionActionPerformed
        try {
            c = new Cancion(JT_TituloCancion.getText(), JT_ReferenciaSingle.getText(), JT_DuracionCancion.getText());
            l = new Singles(c, JT_Titulo.getText(), JT_Fecha.getText(), 0, "Single");
            //lanzamientos.add(l);

                String titulo, ref, dur;
                titulo = JT_TituloCancion.getText();
                ref = JT_ReferenciaSingle.getText();
                dur = JT_DuracionCancion.getText();
                Cancion can = new Cancion(titulo,ref,dur);
                canciones.add(can);
                cancion.escribirArchivocancion();

                String tit, fecha;
                int  likes;
                tit = JT_TituloCancion.getText();
                fecha = JT_Fecha.getText();
                likes= 0;
                Lanzamiento sin = new Singles(can,tit, fecha, likes, "Album");
                lanzamiento.getLanzamientos().add(sin);
                lanzamiento.escribirArchivoLan();
            JOptionPane.showMessageDialog(JD_NuevoLanzamiento, "Single creado con exito");

            DefaultTreeModel modelo = (DefaultTreeModel) jTree1.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
            DefaultMutableTreeNode nodoNombre;
            nodoNombre = new DefaultMutableTreeNode(l);
            switch (CB_Tipo.getSelectedItem().toString()) {
                case "Single":
                    ((DefaultMutableTreeNode) raiz.getChildAt(1)).add(nodoNombre);
                    break;
            }
            modelo.reload();
            JT_TituloCancion.setText("");
            JT_ReferenciaSingle.setText("");
            JT_DuracionCancion.setText("");
            JT_Titulo.setText("");
            JT_Fecha.setText("");
            JD_NuevoLanzamiento.setVisible(false);
            JF_Artista.pack();
            JF_Artista.setLocationRelativeTo(this);
            JF_Artista.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            JF_Artista.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_JB_CrearCancionActionPerformed

    private void JB_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_LoginActionPerformed
        try {
            if (JT_UserLogin.getText().equals("") || PF_Login.getText().equals("")) {
                JOptionPane.showMessageDialog(JP_Login, "Uno de los campos esta vacio");
            } else if (Correct(PF_Login.getText(), JT_UserLogin.getText()) == true && Artista(JT_UserLogin.getText(), "Artista") == true && Oyente(JT_UserLogin.getText(), "Cliente") == false) {
                this.setVisible(false);
                JF_Artista.pack();
                JF_Artista.setLocationRelativeTo(this);
                JF_Artista.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                JF_Artista.setVisible(true);
            } else if (Correct(PF_Login.getText(), JT_UserLogin.getText()) == true && Artista(JT_UserLogin.getText(), "Artista") == false && Oyente(JT_UserLogin.getText(), "Cliente") == true) {
                this.setVisible(false);
//            } else if (usuarios.isEmpty()) {
//                JOptionPane.showMessageDialog(JP_Login, "Debe crear una cuenta primero");
            } else if (Correct(PF_Login.getText(), JT_UserLogin.getText()) == false && SameUser(JT_UserLogin.getText()) == true) {
                JOptionPane.showMessageDialog(JP_Login, "La contrasena es incorrecta");
            } else if (SameUser(JT_UserLogin.getText()) == false) {
                JOptionPane.showMessageDialog(JP_Login, "La cuenta no existe");
            }
        } catch (Exception e) {
        }


    }//GEN-LAST:event_JB_LoginActionPerformed

    private void JB_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_LoginMouseClicked

    }//GEN-LAST:event_JB_LoginMouseClicked

    private void JB_CrearLanzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CrearLanzaActionPerformed
        JF_Artista.setVisible(false);
        JD_NuevoLanzamiento.pack();
        JD_NuevoLanzamiento.setLocationRelativeTo(this);
        JD_NuevoLanzamiento.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        JD_NuevoLanzamiento.setVisible(true);
    }//GEN-LAST:event_JB_CrearLanzaActionPerformed

    private void MI_PublicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_PublicarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MI_PublicarActionPerformed

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        if (evt.getButton() == 3) {
            int row = jTree1.getClosestRowForLocation(evt.getX(), evt.getY());
            jTree1.setSelectionRow(row);
            Object v1 = jTree1.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() instanceof Singles) {
                selectedhit = (Singles) nodo_seleccionado.getUserObject();

                PP_CrudLanza.show(evt.getComponent(), evt.getX(), evt.getY());
            } else {
            }
        }
    }//GEN-LAST:event_jTree1MouseClicked

    private void JB_CrudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CrudActionPerformed
        JF_Artista.setVisible(false);
        JF_ListaLanzamientos.pack();
        JF_ListaLanzamientos.setLocationRelativeTo(this);
        JF_ListaLanzamientos.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        JF_ListaLanzamientos.setVisible(true);
    }//GEN-LAST:event_JB_CrudActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    public boolean SameUser(String username) throws IOException {
        boolean same = false;
        for (int i = 0; i < usuarios.size(); i++) {
            Usuario user = usuarios.get(i);
            if (user.getUser().equals(username)) {
                same = true;
            }

        }

        return same;
    }

    public boolean Correct(String contra, String username) throws IOException {
        boolean correcto = false;
        for (int i = 0; i < usuarios.size(); i++) {
            Usuario user = usuarios.get(i);
            if (user.getUser().equals(username)) {
                if (user.getContra().equals(contra)) {
                    correcto = true;
                }
            }
        }
        return correcto;
    }

    public boolean Artista(String username, String tipo) {
        boolean Artistas = false;
        for (int i = 0; i < usuarios.size(); i++) {
            Usuario user = usuarios.get(i);
            if (user.getUser().equals(username)) {
                if (user.getTipo().equals(tipo)) {
                    Artistas = true;
                }
            }

        }
        return Artistas;
    }

    public boolean Oyente(String username, String tipo) {
        boolean o = false;
        for (int i = 0; i < usuarios.size(); i++) {
            Usuario user = usuarios.get(i);
            if (user.getUser().equals(username)) {
                if (user.getTipo().equals(tipo)) {
                    o = true;

                }
            }

        }
        return o;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_Tipo;
    private javax.swing.JButton JB_AtrasArtista;
    private javax.swing.JButton JB_AtrasCliente;
    private javax.swing.JButton JB_AtrasNuevoLanza;
    private javax.swing.JButton JB_CrearCancion;
    private javax.swing.JButton JB_CrearLanza;
    private javax.swing.JButton JB_CrearLanzamiento;
    private javax.swing.JButton JB_Crud;
    private javax.swing.JButton JB_Login;
    private javax.swing.JButton JB_SignupArtista;
    private javax.swing.JButton JB_SignupCliente;
    private javax.swing.JDialog JD_Cancion;
    private javax.swing.JDialog JD_NuevoLanzamiento;
    private javax.swing.JFrame JF_Artista;
    private javax.swing.JFrame JF_ListaLanzamientos;
    private javax.swing.JFrame JF_SignupArtista;
    private javax.swing.JFrame JF_SignupCliente;
    private javax.swing.JLabel JL_SignupArtista;
    private javax.swing.JLabel JL_SignupCliente;
    private javax.swing.JPanel JP_Login;
    private javax.swing.JPanel JP_SignupArtista;
    private javax.swing.JTextField JT_DuracionCancion;
    private javax.swing.JTextField JT_Fecha;
    private javax.swing.JTextField JT_NombreArtista;
    private javax.swing.JTextField JT_ReferenciaSingle;
    private javax.swing.JTextField JT_Titulo;
    private javax.swing.JTextField JT_TituloCancion;
    private javax.swing.JTextField JT_UserArtista;
    private javax.swing.JTextField JT_UserCliente;
    private javax.swing.JTextField JT_UserLogin;
    private javax.swing.JMenuItem MI_Editar;
    private javax.swing.JMenuItem MI_Eliminar;
    private javax.swing.JMenuItem MI_Publicar;
    private javax.swing.JPasswordField PF_Login;
    private javax.swing.JPasswordField PF_passArtista;
    private javax.swing.JPasswordField PF_passCliente;
    private javax.swing.JPopupMenu PP_CrudLanza;
    private javax.swing.JSpinner Spinner_EdadArtista;
    private javax.swing.JSpinner Spinner_EdadCliente;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
    Usuario u;
    Lanzamiento l;
    Lanzamiento selectedhit;
    ArrayList<Usuario> usuarios = new ArrayList();
    ArrayList<Lanzamiento> lanzamientos = new ArrayList();
    ArrayList<Cancion> canciones = new ArrayList();
    Cancion c;
    DefaultMutableTreeNode nodo_seleccionado;
    admin ap = new admin("./Usuarios.txt");
    admin cancion = new admin ("./Cancion.txt");
    admin lanzamiento = new admin ("./Lanzamiento.txt");
    
}
